openapi: 3.0.0
info:
  version: '1.0'
  title: Ship With Walmart
  description: >-
    The Ship With Walmart (SWW) APIs enables walmart.com sellers to buy shipping
    at competitively discounted rates directly from Walmart to ship their goods
    to US customers.
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/RET-Marketplace/SWW-ShipWithWalmart/1.0

paths:
  /v3/shipping/labels:
    summary: Create Label
    description: >-
      This API generates shipping labels with the shipment info passed. The
      response to a successful call contains the tracking number with the pdf or
      image type based on the media type passed in Accept header. For eg.
      'Accept'='application/json,application/pdf' will result in pdf media type,
      'Accept'='application/json,image/png' as image png media type and
      'Accept'='application/json' as json response.
    post:
      summary: 'Create Shipping Label'
      description: ''
      parameters: []
      responses:
        default:
          description: Default response
      deprecated: false
      requestBody:
        required: false
        content:
          application/json:
            schema: {}